/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorBaseContainer } from '../models/errorBaseContainer.js';

/**
 * Creates an instance of Common
 */
interface Common {
  /**
   * custom error code for developer or user
   * Note: One of the following values will be returned:
   * 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1010, 1011, 1012, 1014, 1015, 1016
   */
  errorCode: number;
  /**
   * Custom error message <br>
   * Note: One of the following values will be returned:
   *   - Offer does not exist
   *   - Customer does not exist
   *   - Valid from date is invalid
   *   - ValidityPeriod is invalid
   *   - Offer is by default assigned to all customers, which cannot be changed.
   *   - Assignment is not allowed
   *   - Customer assign should have validity dates.
   *   - Customer assign validity start date should be before the validity end date.
   *   - Customer assign validity dates must be between the offer assignable dates.
   *   - Offer validity start date should not be in the past.
   *   - Customer already assigned to this offer.
   *   - Offer module is disabled
   *   - Partner code is not valid for this offer
   *   - Reference ID already used
   *   - Partner assignment already ended for this customer
   */
  message: string;
  error: ErrorBaseContainer;
  additionalProperties?: Record<string, unknown>;
}

export class CommonError extends ApiError<Common> {}
