/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of ConsumersBalances401
 */
interface ConsumersBalances401 {
  errorCode: number;
  message: string;
  error?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export class ConsumersBalances401Error extends ApiError<ConsumersBalances401> {}
