/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of ConsumersBalances404
 */
interface ConsumersBalances404 {
  errorCode: number;
  message: string;
  error?: unknown;
  additionalProperties?: Record<string, unknown>;
}

export class ConsumersBalances404Error extends ApiError<ConsumersBalances404> {}
