/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorItem } from '../models/errorItem.js';
import { JsonApiVersion } from '../models/jsonApiVersion.js';

/**
 * Creates an instance of JsonApi
 */
interface JsonApi {
  jsonapi?: JsonApiVersion;
  errors?: ErrorItem[];
  additionalProperties?: Record<string, unknown>;
}

export class JsonApiError extends ApiError<JsonApi> {}
