/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorInfo } from '../models/errorInfo.js';

/**
 * Creates an instance of ResourceNotFound
 */
interface ResourceNotFound {
  /** HTTP error status code */
  errorCode: number;
  /** HTTP error status message */
  message: string;
  error: ErrorInfo;
  additionalProperties?: Record<string, unknown>;
}

export class ResourceNotFoundError extends ApiError<ResourceNotFound> {}
