/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AuthTokenRequest,
  authTokenRequestSchema,
} from '../models/authTokenRequest.js';
import {
  AuthTokenResponse,
  authTokenResponseSchema,
} from '../models/authTokenResponse.js';
import {
  ExchangeAccessCodeRequest,
  exchangeAccessCodeRequestSchema,
} from '../models/exchangeAccessCodeRequest.js';
import {
  M200UserPartners,
  m200UserPartnersSchema,
} from '../models/m200UserPartners.js';
import {
  RefreshTokenRequest,
  refreshTokenRequestSchema,
} from '../models/refreshTokenRequest.js';
import {
  RefreshTokenResponse,
  refreshTokenResponseSchema,
} from '../models/refreshTokenResponse.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { JsonApiError } from '../errors/jsonApiError.js';

export class AuthorizationApi extends BaseApi {
  /**
   * When partner wants to get the basic public token, to be authorized to perform any other call inside
   * SSO, needs to call this endpoint
   *
   * @param body         Digest data generated using sha256(client_id)
   * @return Response from the API call
   */
  async getAuthorizationToken(
    body: AuthTokenRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AuthTokenResponse>> {
    const req = this.createRequest('POST', '/api/v2/auth/token');
    const mapped = req.prepareArgs({ body: [body, authTokenRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      JsonApiError,
      'Bad Request. If the request is missing the digest field'
    );
    req.throwOn(
      401,
      JsonApiError,
      'Unauthorized. If the digest provided is not valid'
    );
    req.throwOn(500, JsonApiError, 'Any unexpected error');
    req.authenticate(false);
    return req.callAsJson(authTokenResponseSchema, requestOptions);
  }

  /**
   * This endpoint allows to given an access code to retrieve an user profile with a pair of valid tokens.
   * In this end point, accessCode can be exchanged for an accessToken which is user-authorization-token.
   *
   * @param authorization Basic Public token which was generated with auth/token
   *                                                          end point.
   * @param body          Exchange access code data
   * @return Response from the API call
   */
  async exchangeAccessCode(
    authorization: string,
    body: ExchangeAccessCodeRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<M200UserPartners>> {
    const req = this.createRequest('POST', '/api/v2/auth/exchangeAccessCode');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, exchangeAccessCodeRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      401,
      JsonApiError,
      'Unauthorized. If making the call with an invalid token'
    );
    req.throwOn(
      404,
      JsonApiError,
      'Not found. If the access code is not in the database'
    );
    req.throwOn(500, JsonApiError, 'Any unexpected error');
    req.authenticate([{ publicBasicToken: true }]);
    return req.callAsJson(m200UserPartnersSchema, requestOptions);
  }

  /**
   * When an access token has expired, a partner that wants to get a new pair of valid tokens to go on
   * performing operations against SSO needs to call this endpoint.
   *
   * @param authorization Basic Public token which was generated with auth/token end
   *                                                    point.
   * @param body
   * @return Response from the API call
   */
  async refresh(
    authorization: string,
    body?: RefreshTokenRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RefreshTokenResponse>> {
    const req = this.createRequest('POST', '/api/v2/auth/token/refresh');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, optional(refreshTokenRequestSchema)],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      JsonApiError,
      'Bad Request. The request is missing the Refresh Token field.'
    );
    req.throwOn(
      401,
      JsonApiError,
      'Unauthorized. This response is generated when either the Basic Token is invalid or the Refresh Token is invalid (see examples)'
    );
    req.throwOn(500, JsonApiError, 'Any unexpected error');
    req.authenticate(false);
    return req.callAsJson(refreshTokenResponseSchema, requestOptions);
  }
}
