/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AssignOfferChannel,
  assignOfferChannelSchema,
} from '../models/assignOfferChannel.js';
import {
  CustomerBalances,
  customerBalancesSchema,
} from '../models/customerBalances.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';
import { ConsumersBalances400Error } from '../errors/consumersBalances400Error.js';
import { ConsumersBalances401Error } from '../errors/consumersBalances401Error.js';
import { ConsumersBalances404Error } from '../errors/consumersBalances404Error.js';
import { ConsumersBalances422Error } from '../errors/consumersBalances422Error.js';

export class BalancesApi extends BaseApi {
  /**
   * Retrieve the customer's loyalty point balance
   *
   * @param languageCode             This is a concatenation of language in lower case as per
   *                                                       ISO 639-1 , “-” and country code as per ISO 3166-1 alpha-2.
   * @param userAuthorizationToken   The value of the accessToken retrieved from the
   *                                                       /auth/exchangeAccessCode endpoint. This is referred to as
   *                                                       user-authorization-token where the access is provided by the
   *                                                       end user.
   * @param consumerUuid             SSO uuid of the user signed in with Shell credentials
   *                                                       Format: 32 hexadecimal digits grouped the following way:
   *                                                       xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
   * @param countryCode              The two character ISO 3166-1 alpha-2 [country code](https:
   *                                                       //www.iso.org/iso-3166-country-codes.html).
   * @param xCorrelationId           An unique ID in GUID format in order to track the request.
   * @param channel                  Channel.
   * @param application              String
   * @return Response from the API call
   */
  async getBalanceByUuid(
    languageCode: string,
    userAuthorizationToken: string,
    consumerUuid: string,
    countryCode: string,
    xCorrelationId?: string,
    channel?: AssignOfferChannel,
    application?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CustomerBalances>> {
    const req = this.createRequest('GET', '/consumers/balances');
    req.baseUrl('Shell1');
    const mapped = req.prepareArgs({
      languageCode: [languageCode, string()],
      userAuthorizationToken: [userAuthorizationToken, string()],
      consumerUuid: [consumerUuid, string()],
      countryCode: [countryCode, string()],
      xCorrelationId: [xCorrelationId, optional(string())],
      channel: [channel, optional(assignOfferChannelSchema)],
      application: [application, optional(string())],
    });
    req.header('user-authorization-token', mapped.userAuthorizationToken);
    req.header('consumerUUID', mapped.consumerUuid);
    req.header('country-code', mapped.countryCode);
    req.header('x-correlation-id', mapped.xCorrelationId);
    req.header('channel', mapped.channel);
    req.header('application', mapped.application);
    req.query('language_code', mapped.languageCode);
    req.throwOn(
      400,
      ConsumersBalances400Error,
      'Bad request - The request was not valid. This code is returned when the server has attempted to process the request, but some aspect of the request is not valid, for example an incorrectly formatted resource or an attempt to deploy an invalid event project to the event runtime. Information about the request is provided in the response body, and includes an error code and error message.'
    );
    req.throwOn(
      401,
      ConsumersBalances401Error,
      'Unauthorized request, Missing Authorization header, or expired authorization token etc. It is returned from the application server \nwhen application security is enabled, and authorization information was missing from the request.\n'
    );
    req.throwOn(
      404,
      ConsumersBalances404Error,
      'Not found - the server can not find the requested resource.'
    );
    req.throwOn(
      422,
      ConsumersBalances422Error,
      'Unprocessable Entity (WebDAV). If you are receiving an HTTP 422 - Unprocessable Entity error, \nthere are several possibilities for why it might be occurring-<br>\n - You are sending in a payload that is not valid JSON. <br> \n - You are sending HTTP headers, such as Content-Type or Accept, which specify a value other than application/json. <br>\n - The request may be valid JSON, but there is something wrong with the content. \n'
    );
    req.throwOn(
      429,
      ApiError,
      "Rate limit hit. See the Retry-After header to specify a delay, but note that there is no guarantee that subsequent requests won't be limited."
    );
    req.throwOn(
      500,
      ApiError,
      'Internal error - the server encountered an unexpected condition that prevented it from fulfilling the request.'
    );
    req.authenticate([
      { customerHeader: true, clientAuthorizationToken: true },
    ]);
    return req.callAsJson(customerBalancesSchema, requestOptions);
  }
}
