/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { OauthToken, oauthTokenSchema } from '../models/oauthToken.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { OauthProviderError } from '../errors/oauthProviderError.js';

export class OauthAuthorizationApi extends BaseApi {
  /**
   * Create a new OAuth 2 token.
   *
   * @param authorization Authorization header in Basic auth format
   * @param scope         Requested scopes as a space-delimited list.
   * @return Response from the API call
   */
  async requestTokenClientAuthorizationToken(
    authorization: string,
    scope?: string,
    fieldParameters?: Record<string, unknown>,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<OauthToken>> {
    const req = this.createRequest('POST', '/v2/oauth/token');
    req.baseUrl('OAuth Server');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      scope: [scope, optional(string())],
    });
    req.header('Authorization', mapped.authorization);
    req.form({
      grant_type: 'client_credentials',
      scope: mapped.scope,
      ...fieldParameters,
    });
    req.throwOn(400, OauthProviderError, 'OAuth 2 provider returned an error.');
    req.throwOn(
      401,
      OauthProviderError,
      'OAuth 2 provider says client authentication failed.'
    );
    req.authenticate(false);
    return req.callAsJson(oauthTokenSchema, requestOptions);
  }
}
