/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AssignOfferChannel,
  assignOfferChannelSchema,
} from '../models/assignOfferChannel.js';
import { Offer, offerSchema } from '../models/offer.js';
import {
  OfferAssignment,
  offerAssignmentSchema,
} from '../models/offerAssignment.js';
import { optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';
import { CommonError } from '../errors/commonError.js';

export class OfferApi extends BaseApi {
  /**
   * Assigning a partner based offer to a customer by the partner
   *
   * @param languageCode             This is a concatenation of language in lower case as
   *                                                           per ISO 639-1 , “-” and country code as per ISO 3166-1
   *                                                           alpha-2.
   * @param userAuthorizationToken   The value of the `accessToken` retrieved from the
   *                                                           `/auth/exchangeAccessCode` endpoint. This is referred to
   *                                                           as user-authorization-token where the access is provided
   *                                                           by the end user.
   * @param countryCode              Two character ISO 3166-1 alpha-2 country code.
   * @param xCorrelationId           An unique ID in GUID format in order to track the
   *                                                           request.
   * @param channel                  Channel.
   * @param application              String
   * @param body                     assign offer to customer
   * @return Response from the API call
   */
  async assignPartnerOffer(
    languageCode: string,
    userAuthorizationToken: string,
    countryCode: string,
    xCorrelationId?: string,
    channel?: AssignOfferChannel,
    application?: string,
    body?: OfferAssignment,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Offer>> {
    const req = this.createRequest('POST', '/consumers/offers');
    req.baseUrl('Shell1');
    const mapped = req.prepareArgs({
      languageCode: [languageCode, string()],
      userAuthorizationToken: [userAuthorizationToken, string()],
      countryCode: [countryCode, string()],
      xCorrelationId: [xCorrelationId, optional(string())],
      channel: [channel, optional(assignOfferChannelSchema)],
      application: [application, optional(string())],
      body: [body, optional(offerAssignmentSchema)],
    });
    req.header('user-authorization-token', mapped.userAuthorizationToken);
    req.header('country-code', mapped.countryCode);
    req.header('Content-Type', 'application/json');
    req.header('x-correlation-id', mapped.xCorrelationId);
    req.header('channel', mapped.channel);
    req.header('application', mapped.application);
    req.query('language_code', mapped.languageCode);
    req.json(mapped.body);
    req.throwOn(
      400,
      CommonError,
      'Bad request as certain mandatory parameters were not provided by the client in the request.'
    );
    req.throwOn(
      401,
      CommonError,
      'Unauthorized request, Missing Authorization header, or expired authorization token.'
    );
    req.throwOn(404, CommonError, 'Offer/Customer does not exist.');
    req.throwOn(
      422,
      CommonError,
      'All offer assignment based error what it caused by the "Offer"'
    );
    req.throwOn(
      429,
      ApiError,
      "Rate limit hit. See Retry-After header for a minimum amount of delay, but note that there is no guarantee\nthat subsequent request won't be limited.\n"
    );
    req.throwOn(500, ApiError, 'Internal server error');
    req.authenticate([{ clientAuthorizationToken: true }]);
    return req.callAsJson(offerSchema, requestOptions);
  }

  /**
   * Revoking a partner based offer from customer by Partner.
   *
   * @param languageCode               This is a concatenation of language in lower case as per
   *                                                         ISO 639-1 , “-” and country code as per ISO 3166-1 alpha-2.
   * @param userAuthorizationToken     The value of the `accessToken` retrieved from the
   *                                                         `/auth/exchangeAccessCode` endpoint. This is referred to
   *                                                         as user-authorization-token where the access is provided
   *                                                         by the end user.
   * @param clientAuthorizationToken   The value of the `accessToken` retrieved from the
   *                                                         `/oauth/token` endpoint. This is client authorization
   *                                                         between Shell and Partner system.
   * @param countryCode                Two character ISO 3166-1 alpha-2 country code.
   * @param consumerUuid               SSO uuid of the user signed in with Shell credentials.
   * @param partnerReferenceId         Unique Reference ID for the transaction which was used
   *                                                         when assigning the offer from the partner in Assign Offer
   *                                                         API
   * @param xCorrelationId             An unique ID in GUID format in order to track the request.
   * @param channel                    Channel.
   * @param application                String
   * @return Response from the API call
   */
  async revokePartnerOffer(
    languageCode: string,
    userAuthorizationToken: string,
    clientAuthorizationToken: string,
    countryCode: string,
    consumerUuid: string,
    partnerReferenceId: string,
    xCorrelationId?: string,
    channel?: AssignOfferChannel,
    application?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Offer>> {
    const req = this.createRequest('DELETE', '/consumers/offers');
    req.baseUrl('Shell1');
    const mapped = req.prepareArgs({
      languageCode: [languageCode, string()],
      userAuthorizationToken: [userAuthorizationToken, string()],
      clientAuthorizationToken: [clientAuthorizationToken, string()],
      countryCode: [countryCode, string()],
      consumerUuid: [consumerUuid, string()],
      partnerReferenceId: [partnerReferenceId, string()],
      xCorrelationId: [xCorrelationId, optional(string())],
      channel: [channel, optional(assignOfferChannelSchema)],
      application: [application, optional(string())],
    });
    req.header('user-authorization-token', mapped.userAuthorizationToken);
    req.header('client-authorization-token', mapped.clientAuthorizationToken);
    req.header('country-code', mapped.countryCode);
    req.header('consumerUUID', mapped.consumerUuid);
    req.header('partnerReferenceId', mapped.partnerReferenceId);
    req.header('x-correlation-id', mapped.xCorrelationId);
    req.header('channel', mapped.channel);
    req.header('application', mapped.application);
    req.query('language_code', mapped.languageCode);
    req.throwOn(
      400,
      CommonError,
      'Bad request as certain mandatory parameters were not provided by the client in the request.'
    );
    req.throwOn(
      401,
      CommonError,
      'Unauthorized request, Missing Authorization header, or expired authorization token.'
    );
    req.throwOn(404, CommonError, 'Offer/Customer does not exist.');
    req.throwOn(
      422,
      CommonError,
      'All offer assignment based error what it caused by the "Offer"'
    );
    req.throwOn(
      429,
      ApiError,
      "Rate limit hit. See Retry-After header for a minimum amount of delay, but note that there is no guarantee\nthat subsequent request won't be limited.\n"
    );
    req.throwOn(500, ApiError, 'Internal server error');
    req.authenticate([{ clientAuthorizationToken: true }]);
    return req.callAsJson(offerSchema, requestOptions);
  }
}
