/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AccessCodeResponse,
  accessCodeResponseSchema,
} from '../models/accessCodeResponse.js';
import { optional, string, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';
import { JsonApiError } from '../errors/jsonApiError.js';

export class ProfileManagementApi extends BaseApi {
  /**
   * This endpoint allows get the Access Code from /api/v2/auth/accessCode endpoint. Use the
   * *accessToken* obtained using /api/v2/auth/exchangeAccessCode as Bearer in the Authorization header.
   *
   * @param xSsoMarket    A combination of [language code](https://www.iso.org/standard/22109.html) (lower
   *                                 case) and [country code](https://www.iso.org/iso-3166-country-codes.html) (upper
   *                                 case), separated by a hyphen. For example: **en-TH**.
   * @param authorization The input value is **Bearer {{accessToken}}**. The value of *accessToken* is
   *                                 retrieved from the /auth/exchangeAccessCode endpoint.
   * @return Response from the API call
   */
  async accessCode(
    xSsoMarket: string,
    authorization: unknown,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccessCodeResponse>> {
    const req = this.createRequest('POST', '/api/v2/auth/accessCode');
    const mapped = req.prepareArgs({
      xSsoMarket: [xSsoMarket, string()],
      authorization: [authorization, optional(unknown())],
    });
    req.header('x-sso-market', mapped.xSsoMarket);
    req.header('Authorization', mapped.authorization);
    req.throwOn(401, ApiError, 'Unauthorized');
    req.throwOn(500, JsonApiError, 'Any unexpected error');
    req.authenticate(false);
    return req.callAsJson(accessCodeResponseSchema, requestOptions);
  }
}
