/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AssignOfferChannel,
  assignOfferChannelSchema,
} from '../models/assignOfferChannel.js';
import {
  RedemptionRequest,
  redemptionRequestSchema,
} from '../models/redemptionRequest.js';
import {
  RedemptionResponse,
  redemptionResponseSchema,
} from '../models/redemptionResponse.js';
import { number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';
import { ConsumersBalances400Error } from '../errors/consumersBalances400Error.js';

export class RedemptionApi extends BaseApi {
  /**
   * Point redemption API for customers to redeem loyalty points via the partner channel
   *
   * @param languageCode             A combination of [language code](https://www.iso.
   *                                                             org/standard/22109.html) (lower case) and [country
   *                                                             code](https://www.iso.org/iso-3166-country-codes.html)
   *                                                             (upper case), separated by a hyphen.
   * @param userAuthorizationToken   The value of the accessToken retrieved from the
   *                                                             /auth/exchangeAccessCode endpoint. This is referred to
   *                                                             as user-authorization-token where the access is
   *                                                             provided by the end user.
   * @param consumerUuid             SSO uuid of the user signed in with Shell credentials
   *                                                             Format: 32 hexadecimal digits grouped the following
   *                                                             way: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
   * @param countryCode              The two character ISO 3166-1 alpha-2 [country
   *                                                             code](https://www.iso.org/iso-3166-country-codes.html).
   * @param xCorrelationId           An unique ID in GUID format in order to track the
   *                                                             request.
   * @param channel                  Channel.
   * @param application              String
   * @param retryAfter               Retry the operation after a specified number of
   *                                                             seconds have elapsed.
   * @param body                     Redeem a customer's loyalty points
   * @return Response from the API call
   */
  async pointRedemption(
    languageCode: string,
    userAuthorizationToken: string,
    consumerUuid: string,
    countryCode: string,
    xCorrelationId?: string,
    channel?: AssignOfferChannel,
    application?: string,
    retryAfter?: number,
    body?: RedemptionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RedemptionResponse>> {
    const req = this.createRequest('POST', '/consumers/redemption');
    req.baseUrl('Shell1');
    const mapped = req.prepareArgs({
      languageCode: [languageCode, string()],
      userAuthorizationToken: [userAuthorizationToken, string()],
      consumerUuid: [consumerUuid, string()],
      countryCode: [countryCode, string()],
      xCorrelationId: [xCorrelationId, optional(string())],
      channel: [channel, optional(assignOfferChannelSchema)],
      application: [application, optional(string())],
      retryAfter: [retryAfter, optional(number())],
      body: [body, optional(redemptionRequestSchema)],
    });
    req.header('user-authorization-token', mapped.userAuthorizationToken);
    req.header('consumerUUID', mapped.consumerUuid);
    req.header('country-code', mapped.countryCode);
    req.header('Content-Type', 'application/json');
    req.header('x-correlation-id', mapped.xCorrelationId);
    req.header('channel', mapped.channel);
    req.header('application', mapped.application);
    req.header('Retry-After', mapped.retryAfter);
    req.query('language_code', mapped.languageCode);
    req.json(mapped.body);
    req.throwOn(
      400,
      ConsumersBalances400Error,
      'Bad request - The request was not valid. This code is returned when the server has attempted to process the request, but some aspect of the request is not valid, for example an incorrectly formatted resource or an attempt to deploy an invalid event project to the event runtime. Information about the request is provided in the response body, and includes an error code and error message.'
    );
    req.throwOn(
      401,
      ConsumersBalances400Error,
      'Unauthorized request, Missing Authorization header, or expired authorization token etc. It is returned from the application server \nwhen application security is enabled, and authorization information was missing from the request.\n'
    );
    req.throwOn(
      404,
      ConsumersBalances400Error,
      'Not found - the server can not find the requested resource.'
    );
    req.throwOn(
      422,
      ConsumersBalances400Error,
      'Unprocessable Entity (WebDAV). If you are receiving an HTTP 422 - Unprocessable Entity error, \nthere are several possibilities for why it might be occurring-<br>\n - You are sending in a payload that is not valid JSON. <br> \n - You are sending HTTP headers, such as Content-Type or Accept, which specify a value other than application/json. <br>\n - The request may be valid JSON, but there is something wrong with the content. \n'
    );
    req.throwOn(
      429,
      ApiError,
      "Rate limit hit. See the Retry-After header to specify a delay, but note that there is no guarantee that subsequent requests won't be limited."
    );
    req.throwOn(500, ApiError, 'Internal server error');
    req.authenticate([{ clientAuthorizationToken: true }]);
    return req.callAsJson(redemptionResponseSchema, requestOptions);
  }
}
