/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  TransactionsResponse,
  transactionsResponseSchema,
} from '../models/transactionsResponse.js';
import {
  TransactionTypeFilter,
  transactionTypeFilterSchema,
} from '../models/transactionTypeFilter.js';
import {
  boolean,
  nullable,
  number,
  optional,
  string,
  unknown,
} from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ApiError } from '@apimatic/core';
import { ErrorResponseError } from '../errors/errorResponseError.js';
import { ResourceNotFoundError } from '../errors/resourceNotFoundError.js';

export class TransactionApi extends BaseApi {
  /**
   * This API is used to fetch and retrieve the list of transactions of a customer.
   *
   * Example cURL request:
   *
   * curl --location 'https://api-test.shell.com/loyalty/v1/consumers/transactionsL?language_code=pl-PL'
   * \
   * --header 'country-code: PL' \
   * --header 'user-authorization-token: Bearer clk6qsn0z000o1rpactbsyu93' \
   * --header 'client-authorization-token: Bearer fmVQg8M2F2NGeI3RE18G8R8luKTk' \
   * --header 'language: en' \
   * --header 'application: PARTNER' \
   * --header 'channel: PARTNER' \
   * --header 'consumerUUID: bd68f27f-80f7-440a-b096-f65155161345'
   *
   *
   * @param countryCode              This represents the ISO 3166-1 standard Alpha-2
   *                                                                 code of the Country, which is the first two
   *                                                                 characters of the country code.
   * @param consumerUuid             This is the consumer's or customer's unique SSO
   *                                                                 UUID.
   * @param userAuthorizationToken   This is the consumer's SSO access, which you
   *                                                                 retrieved from /auth/exchangeAccessCode endpoint
   *                                                                 prefixed by Bearer.
   * @param application              This is the calling application.
   * @param languageCode             This is a concatenation of language in lower case
   *                                                                 as per ISO 639-1 , “-” and country code as per ISO
   *                                                                 3166-1 alpha-2. For example: en-GB.
   * @param language                 This is the language in ISO 639-1 2 letter code
   *                                                                 format.
   * @param channel                  Channel.
   * @param page                     The page number, which needs to be retrieved.
   * @param limit                    The maximum number of resources to be sent across
   *                                                                 all pages.
   * @param offset                   This is used to skip a certain number of
   *                                                                 resources at the start of each page.
   * @param pageSize                 This is the maximum number of resources to be
   *                                                                 sent in each page of the response.
   * @param transactionType          This is the type of the transaction. If the
   *                                                                 parameter is empty, it means that “ALL” queries.
   * @param fromDateTime             This is the datetime from which the transaction
   *                                                                 details are required.
   * @param toDateTime               This is the datetime until which the transaction
   *                                                                 details are required.
   * @param filterByPartnerCode      This is used to filter the transactions based on
   *                                                                 partnerCode. If true, return the transactions
   *                                                                 related to partnerCode. If false, return all
   *                                                                 transactions.
   * @return Response from the API call
   */
  async getTransactionsL(
    countryCode: string,
    consumerUuid: string,
    userAuthorizationToken: string,
    application: string,
    languageCode: string,
    language?: string,
    channel?: unknown,
    page?: number,
    limit?: number,
    offset?: number,
    pageSize?: number,
    transactionType?: TransactionTypeFilter | null,
    fromDateTime?: string | null,
    toDateTime?: string | null,
    filterByPartnerCode?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TransactionsResponse>> {
    const req = this.createRequest('GET', '/v1/consumers/transactionsL');
    req.baseUrl('Shell2');
    const mapped = req.prepareArgs({
      countryCode: [countryCode, string()],
      consumerUuid: [consumerUuid, string()],
      userAuthorizationToken: [userAuthorizationToken, string()],
      application: [application, string()],
      languageCode: [languageCode, string()],
      language: [language, optional(string())],
      channel: [channel, optional(unknown())],
      page: [page, optional(number())],
      limit: [limit, optional(number())],
      offset: [offset, optional(number())],
      pageSize: [pageSize, optional(number())],
      transactionType: [
        transactionType,
        optional(nullable(transactionTypeFilterSchema)),
      ],
      fromDateTime: [fromDateTime, optional(nullable(string()))],
      toDateTime: [toDateTime, optional(nullable(string()))],
      filterByPartnerCode: [filterByPartnerCode, optional(boolean())],
    });
    req.header('country-code', mapped.countryCode);
    req.header('consumerUUID', mapped.consumerUuid);
    req.header('user-authorization-token', mapped.userAuthorizationToken);
    req.header('application', mapped.application);
    req.header('language', mapped.language);
    req.header('channel', mapped.channel);
    req.query('language_code', mapped.languageCode);
    req.query('page', mapped.page);
    req.query('limit', mapped.limit);
    req.query('offset', mapped.offset);
    req.query('pageSize', mapped.pageSize);
    req.query('transactionType', mapped.transactionType);
    req.query('fromDateTime', mapped.fromDateTime);
    req.query('toDateTime', mapped.toDateTime);
    req.query('filterByPartnerCode', mapped.filterByPartnerCode);
    req.throwOn(
      400,
      ErrorResponseError,
      'Bad request - The request was not valid. This code is returned when the server has attempted to process the request, but some aspect of the request is not valid, for example an incorrectly formatted resource or an attempt to deploy an invalid event project to the event runtime. Information about the request is provided in the response body and includes an error code and error message.'
    );
    req.throwOn(
      401,
      ErrorResponseError,
      'Unauthorized request, Missing Authorization header, or expired authorization token etc. It is returned from the application server\nwhen application security is enabled, and authorization information was missing from the request.\n'
    );
    req.throwOn(404, ResourceNotFoundError, 'Not Found.');
    req.throwOn(
      422,
      ApiError,
      "'Unprocessable Entity (WebDAV). If you are receiving an HTTP 422 - Unprocessable Entity error, there are several possibilities for why it might be occurring: <br><br> -You are sending in a payload that is not valid JSON <br><br> -You are sending HTTP headers, such as Content-Type or Accept, which specify a value other than application/json <br><br> -The request may be valid JSON, but there is something wrong with the content.\n"
    );
    req.throwOn(
      429,
      ApiError,
      "Rate limit hit. See Retry-After header for a minimum amount of delay, but note that there is no guarantee\nthat subsequent request won't be limited.\n"
    );
    req.throwOn(500, ApiError, 'Internal server error.');
    req.authenticate([{ clientAuthorizationToken: true }]);
    return req.callAsJson(transactionsResponseSchema, requestOptions);
  }
}
