/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AccessCodeResponse {
  /** AccessCode provided by Shell after it redirects the user to the partner's URL. */
  accessCode?: string;
  /** Indicates the number of seconds until the accessCode expires */
  expiresIn?: number;
  additionalProperties?: Record<string, unknown>;
}

export const accessCodeResponseSchema: Schema<AccessCodeResponse> = typedExpandoObject(
  {
    accessCode: ['accessCode', optional(string())],
    expiresIn: ['expiresIn', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
