/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AssignOfferChannel
 */
export enum AssignOfferChannel {
  Partner = 'PARTNER',
}

/**
 * Schema for AssignOfferChannel
 */
export const assignOfferChannelSchema: Schema<AssignOfferChannel> = stringEnum(
  AssignOfferChannel
);
