/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AuthTokenResponse {
  /** Your Basic public token which needs to be used in the auth/ExchangeAccessCode. */
  token?: string;
  /** Type of the token. */
  tokenType?: string;
  /** With value **unlimited** it means this token will never expire */
  expiresIn?: string;
  /** States the name of the partner to which the digest used belongs */
  owner?: string;
  additionalProperties?: Record<string, unknown>;
}

export const authTokenResponseSchema: Schema<AuthTokenResponse> = typedExpandoObject(
  {
    token: ['token', optional(string())],
    tokenType: ['tokenType', optional(string())],
    expiresIn: ['expiresIn', optional(string())],
    owner: ['owner', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
