/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface AuthTokenRequest {
  digest?: string;
  additionalProperties?: Record<string, unknown>;
}

export const authTokenRequestSchema: Schema<AuthTokenRequest> = typedExpandoObject(
  { digest: ['digest', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
