/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Fault, faultSchema } from './fault.js';

/** Request is missing a parameter so the server cannot proceed with the request. */
export interface BadRequestError {
  fault?: Fault;
}

export const badRequestErrorSchema: Schema<BadRequestError> = lazy(() =>
  object({ fault: ['fault', optional(faultSchema)] })
);
