/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BalanceState
 */
export enum BalanceState {
  Available = 'AVAILABLE',
  Expiring = 'EXPIRING',
  Reserved = 'RESERVED',
  Target = 'TARGET',
  Boost = 'BOOST',
  Change = 'CHANGE',
  TotalSpent = 'TOTAL_SPENT',
  Earned = 'EARNED',
  Redeemed = 'REDEEMED',
  Total = 'TOTAL',
  Last = 'LAST',
}

/**
 * Schema for BalanceState
 */
export const balanceStateSchema: Schema<BalanceState> = stringEnum(
  BalanceState
);
