/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BalanceCurrencyAmount,
  balanceCurrencyAmountSchema,
} from './balanceCurrencyAmount.js';

/** List of Balances for the customer */
export interface BalanceAmount {
  amounts?: BalanceCurrencyAmount[];
  additionalProperties?: Record<string, unknown>;
}

export const balanceAmountSchema: Schema<BalanceAmount> = lazy(() =>
  typedExpandoObject(
    { amounts: ['amounts', optional(array(balanceCurrencyAmountSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
