/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BalanceCurrencyType
 */
export enum BalanceCurrencyType {
  Qv = 'QV',
  Point = 'POINT',
  Stamp = 'STAMP',
  Airmiles = 'AIRMILES',
  Miles = 'MILES',
  Cash = 'CASH',
  StampCounter = 'STAMP_COUNTER',
  Nbs = 'NBS',
}

/**
 * Schema for BalanceCurrencyType
 */
export const balanceCurrencyTypeSchema: Schema<BalanceCurrencyType> = stringEnum(
  BalanceCurrencyType
);
