/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  BalanceAmountDetail,
  balanceAmountDetailSchema,
} from './balanceAmountDetail.js';
import {
  BalanceCurrencyType,
  balanceCurrencyTypeSchema,
} from './balanceCurrencyType.js';

export interface BalanceCurrencyAmount {
  currencyType: BalanceCurrencyType;
  amounts?: BalanceAmountDetail[];
  additionalProperties?: Record<string, unknown>;
}

export const balanceCurrencyAmountSchema: Schema<BalanceCurrencyAmount> = lazy(
  () =>
    typedExpandoObject(
      {
        currencyType: ['currencyType', balanceCurrencyTypeSchema],
        amounts: ['amounts', optional(array(balanceAmountDetailSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
