/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BalanceState, balanceStateSchema } from './balanceState.js';

export interface BalanceAmountDetail {
  /** Current value of specified balance. */
  amount: number;
  /** State of the points balance amount. */
  state: BalanceState;
  /** Expiration Date in JSON recommended format: “yyyy-MM-ddTHH:mm:ssZ” Nullable. */
  dateTime: string;
  /** Date as Unix epoch (UTC). */
  dateTimestamp: bigint;
  /** Point to cash exchange amnount. */
  cashAmount?: number;
  /** Period of expiration, minimum value is 1. Seralized only when it’s not null. */
  period?: number;
  /** The list of numbers describes an index of boost’s position in qualifying visit, Seralized only when it’s not null and not empty. */
  position?: number[];
  additionalProperties?: Record<string, unknown>;
}

export const balanceAmountDetailSchema: Schema<BalanceAmountDetail> = typedExpandoObject(
  {
    amount: ['amount', number()],
    state: ['state', balanceStateSchema],
    dateTime: ['dateTime', string()],
    dateTimestamp: ['dateTimestamp', bigint()],
    cashAmount: ['cashAmount', optional(number())],
    period: ['period', optional(number())],
    position: ['position', optional(array(number()))],
  },
  'additionalProperties',
  optional(unknown())
);
