/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface ClientAuthTokenRequest {
  /** Client ID provided by Shell */
  clientId: string;
  /** Client Secret provided by Shell */
  clientSecret: string;
  /** Grant type value for access */
  grantType: string;
}

export const clientAuthTokenRequestSchema: Schema<ClientAuthTokenRequest> = object(
  {
    clientId: ['client_id', string()],
    clientSecret: ['client_secret', string()],
    grantType: ['grant_type', string()],
  }
);
