/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** currencyData is only filled, where there is possible non-same currency cross-border transaction */
export interface CurrencyData {
  /** Currency code */
  code: string;
  /** Currency symbol */
  symbol: string;
  /** Currency format (is the symbol after the value) */
  isSuffix: boolean;
  /** Currency format (is there a space between the symbol and the value) */
  hasSpace: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const currencyDataSchema: Schema<CurrencyData> = typedExpandoObject(
  {
    code: ['code', string()],
    symbol: ['symbol', string()],
    isSuffix: ['isSuffix', boolean()],
    hasSpace: ['hasSpace', boolean()],
  },
  'additionalProperties',
  optional(unknown())
);
