/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BalanceAmount, balanceAmountSchema } from './balanceAmount.js';

export interface CustomerBalances {
  /** A list of points balances. Not nullable, an empty array is used instead. */
  balances?: BalanceAmount[];
  additionalProperties?: Record<string, unknown>;
}

export const customerBalancesSchema: Schema<CustomerBalances> = lazy(() =>
  typedExpandoObject(
    { balances: ['balances', optional(array(balanceAmountSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
