/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ErrorSource {
  pointer?: string;
  additionalProperties?: Record<string, unknown>;
}

export const errorSourceSchema: Schema<ErrorSource> = typedExpandoObject(
  { pointer: ['pointer', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
