/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ErrorPresenter {
  /**
   * custom error code for developer or user
   * Note: One of the following values will be returned:
   * 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1010, 1011, 1012, 1014, 1015, 1016
   */
  appErrorCode: string;
  /**
   * Custom error message <br>
   * Note: One of the following values will be returned:
   *   - Offer does not exist
   *   - Customer does not exist
   *   - Valid from date is invalid
   *   - ValidityPeriod is invalid
   *   - Offer is by default assigned to all customers, which cannot be changed.
   *   - Assignment is not allowed
   *   - Customer assign should have validity dates.
   *   - Customer assign validity start date should be before the validity end date.
   *   - Customer assign validity dates must be between the offer assignable dates.
   *   - Offer validity start date should not be in the past.
   *   - Customer already assigned to this offer.
   *   - Offer module is disabled
   *   - Partner code is not valid for this offer
   *   - Reference ID already used
   *   - Partner assignment already ended for this customer
   */
  message: string;
  /** reason for the error */
  reason?: string | null;
  /** subject of the error. Examples will be shared later */
  subject?: string | null;
  /** subject type of the error. Examples will be shared later. */
  subjectType?: string | null;
  /** Type of error. Examples will be shared later. */
  type?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const errorPresenterSchema: Schema<ErrorPresenter> = typedExpandoObject(
  {
    appErrorCode: ['appErrorCode', string()],
    message: ['message', string()],
    reason: ['reason', optional(nullable(string()))],
    subject: ['subject', optional(nullable(string()))],
    subjectType: ['subjectType', optional(nullable(string()))],
    type: ['type', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
