/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ErrorSource, errorSourceSchema } from './errorSource.js';

export interface ErrorItem {
  status?: number;
  title?: string;
  source?: ErrorSource;
  detail?: string;
  additionalProperties?: Record<string, unknown>;
}

export const errorItemSchema: Schema<ErrorItem> = lazy(() =>
  typedExpandoObject(
    {
      status: ['status', optional(number())],
      title: ['title', optional(string())],
      source: ['source', optional(errorSourceSchema)],
      detail: ['detail', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
