/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ErrorPresenter, errorPresenterSchema } from './errorPresenter.js';

export interface ErrorInfo {
  user: ErrorPresenter;
  developer?: ErrorPresenter;
  additionalProperties?: Record<string, unknown>;
}

export const errorInfoSchema: Schema<ErrorInfo> = lazy(() =>
  typedExpandoObject(
    {
      user: ['User', errorPresenterSchema],
      developer: ['Developer', optional(errorPresenterSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
