/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface EvChargingDetails {
  /** Charging point serial ID */
  chargePointSerialId: string;
  /** Charging point connector type */
  chargePointConnectorTypeCd?: string;
  /** Charging point connector description */
  chargePointConnectorTypeDesc?: string;
  /** Date and time at which the transaction started. Format as per ISO 8601 standard. */
  startDateTime: string;
  /** Date and time at which the transaction ended. Format as per ISO 8601 standard. */
  endDateTime: string;
  /** Duration of the transaction in seconds. */
  duration: number;
  additionalProperties?: Record<string, unknown>;
}

export const evChargingDetailsSchema: Schema<EvChargingDetails> = typedExpandoObject(
  {
    chargePointSerialId: ['chargePointSerialId', string()],
    chargePointConnectorTypeCd: [
      'chargePointConnectorTypeCd',
      optional(string()),
    ],
    chargePointConnectorTypeDesc: [
      'chargePointConnectorTypeDesc',
      optional(string()),
    ],
    startDateTime: ['startDateTime', string()],
    endDateTime: ['endDateTime', string()],
    duration: ['duration', number()],
  },
  'additionalProperties',
  optional(unknown())
);
