/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface ExchangeAccessCodeRequest {
  /** AccessCode provided by Shell after it redirects the user to the partner's URL. */
  accessCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const exchangeAccessCodeRequestSchema: Schema<ExchangeAccessCodeRequest> = typedExpandoObject(
  { accessCode: ['accessCode', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
