/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FaultDetail, faultDetailSchema } from './faultDetail.js';

export interface Fault {
  /** The description of the error. */
  faultstring?: string;
  detail?: FaultDetail;
  additionalProperties?: Record<string, unknown>;
}

export const faultSchema: Schema<Fault> = lazy(() =>
  typedExpandoObject(
    {
      faultstring: ['faultstring', optional(string())],
      detail: ['detail', optional(faultDetailSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
