/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface FaultDetail {
  /** The error code. */
  errorcode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const faultDetailSchema: Schema<FaultDetail> = typedExpandoObject(
  { errorcode: ['errorcode', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
