/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface JsonApiVersion {
  version?: string;
  additionalProperties?: Record<string, unknown>;
}

export const jsonApiVersionSchema: Schema<JsonApiVersion> = typedExpandoObject(
  { version: ['version', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
