/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface LoyaltyCardInfo {
  /** Loyalty card of the transaction. */
  loyaltyCard?: string;
  additionalProperties?: Record<string, unknown>;
}

export const loyaltyCardInfoSchema: Schema<LoyaltyCardInfo> = typedExpandoObject(
  { loyaltyCard: ['loyaltyCard', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
