/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface M200UserPartners {
  uuid: string;
  userStatus: string;
  market?: unknown;
  accessToken: string;
  refreshToken: string;
  additionalProperties?: Record<string, unknown>;
}

export const m200UserPartnersSchema: Schema<M200UserPartners> = typedExpandoObject(
  {
    uuid: ['uuid', string()],
    userStatus: ['userStatus', string()],
    market: ['market', optional(unknown())],
    accessToken: ['accessToken', string()],
    refreshToken: ['refreshToken', string()],
  },
  'additionalProperties',
  optional(unknown())
);
