/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Fault, faultSchema } from './fault.js';

/** An error response. */
export interface MethodNotAllowedError {
  fault?: Fault;
}

export const methodNotAllowedErrorSchema: Schema<MethodNotAllowedError> = lazy(
  () => object({ fault: ['fault', optional(faultSchema)] })
);
