/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Fault, faultSchema } from './fault.js';

/** An error response. */
export interface NotFoundError {
  fault?: Fault;
}

export const notFoundErrorSchema: Schema<NotFoundError> = lazy(() =>
  object({ fault: ['fault', optional(faultSchema)] })
);
