/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ErrorInfo, errorInfoSchema } from './errorInfo.js';

export interface NotFoundErrorResponse {
  /** HTTP error code 404 */
  errorCode: number;
  /** HTTP error message - Not Found */
  message: string;
  error: ErrorInfo;
  additionalProperties?: Record<string, unknown>;
}

export const notFoundErrorResponseSchema: Schema<NotFoundErrorResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        errorCode: ['errorCode', number()],
        message: ['message', string()],
        error: ['error', errorInfoSchema],
      },
      'additionalProperties',
      optional(unknown())
    )
);
