/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface OfferBase {
  /** Offer ID provided upon offer configuration */
  offerId: bigint;
  /** Unique Reference ID for the transaction from the partner. Used to identify duplicate requests. */
  referenceId: string;
  /** Title of the partner's offer, given upon configuration */
  title: string;
  /** Description of the partner's offer, set up upon offer configuration */
  description: string;
  additionalProperties?: Record<string, unknown>;
}

export const offerBaseSchema: Schema<OfferBase> = typedExpandoObject(
  {
    offerId: ['offerId', bigint()],
    referenceId: ['referenceId', string()],
    title: ['title', string()],
    description: ['description', string()],
  },
  'additionalProperties',
  optional(unknown())
);
