/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Offer {
  /** Offer ID provided upon offer configuration */
  offerId: bigint;
  /** Unique Reference ID for the transaction from the partner. Used to identify duplicate requests. */
  referenceId: string;
  /** Title of the partner's offer, given upon configuration */
  title: string;
  /** Description of the partner's offer, set up upon offer configuration */
  description: string;
  /**
   * Offer validity start date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
   * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered UTC.
   * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC. Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or later) than UTC
   */
  validFrom: string;
  /**
   * Offer validity end date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
   * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered UTC.
   * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC. Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or later) than UTC
   * Nullable field value, in case of the offer has infinite valid to.
   */
  validTo?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const offerSchema: Schema<Offer> = typedExpandoObject(
  {
    offerId: ['offerId', bigint()],
    referenceId: ['referenceId', string()],
    title: ['title', string()],
    description: ['description', string()],
    validFrom: ['validFrom', string()],
    validTo: ['validTo', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
