/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface OfferInfo {
  /** Discount value of the offer */
  discountValue: number;
  /** Total amount of points awarded for the given product code. */
  loyaltyOfferAmount?: number;
  /** Unique ID of the voucher/coupon. */
  loyaltyOfferCode?: string;
  /** Name of loyalty offer */
  loyaltyOfferDescription?: string;
  /** Loyalty Offer ID */
  loyaltyOfferId: string;
  /** Loyalty offer type */
  loyaltyOfferType?: string;
  /** Loyalty Scheme code */
  loyaltySchemeCode?: string;
  /** Offer/reward name */
  reason: string;
  additionalProperties?: Record<string, unknown>;
}

export const offerInfoSchema: Schema<OfferInfo> = typedExpandoObject(
  {
    discountValue: ['discountValue', number()],
    loyaltyOfferAmount: ['loyaltyOfferAmount', optional(number())],
    loyaltyOfferCode: ['loyaltyOfferCode', optional(string())],
    loyaltyOfferDescription: ['loyaltyOfferDescription', optional(string())],
    loyaltyOfferId: ['loyaltyOfferID', string()],
    loyaltyOfferType: ['loyaltyOfferType', optional(string())],
    loyaltySchemeCode: ['loyaltySchemeCode', optional(string())],
    reason: ['reason', string()],
  },
  'additionalProperties',
  optional(unknown())
);
