/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface OfferLanguage {
  /** Unique Id of the offer */
  id: string;
  /** Title of the offer */
  title: string;
  /** Description of the offer */
  description: string;
  /** Custom text of the offer */
  customText: string;
  additionalProperties?: Record<string, unknown>;
}

export const offerLanguageSchema: Schema<OfferLanguage> = typedExpandoObject(
  {
    id: ['id', string()],
    title: ['title', string()],
    description: ['description', string()],
    customText: ['customText', string()],
  },
  'additionalProperties',
  optional(unknown())
);
