/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface OfferAssignment {
  /** Unique Reference ID for the transaction from the partner. Used to identify duplicate requests. */
  referenceId: string;
  /**
   * SSO uuid of the user signed in with Shell credentials
   * Format: 32 hexadecimal digits grouped the following way: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
   */
  consumerUuid: string;
  /**
   * Offer identifier shared by Shell.
   * Format: string(30)
   */
  offerId: string;
  /**
   * Offer validity start date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
   * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered UTC.
   * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC. Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or later) than UTC
   */
  validFrom?: string;
  /**
   * Offer validity period (Number of days)
   * If validityPeriod is greater than zero, validTo will be ignored.
   * The offer will be valid till:
   *   validfrom + validityperiod
   *  If the resulting valid to date would be during the day, then its validity is modified to last until midnight in the timezone of the validFrom date.
   *  E.g. If valiFrom is "2021-03-08T17:12:55Z+01:00" (Central European time) and validtyPeriod is 3 then the offer will be valid till "2021-03-11T23:59:59Z+01:00" (Central European Time)
   */
  validityPeriod?: number;
  /**
   * Offer validity end date in JSON recommended format: "yyyy-MM-ddTHH:mm:ssZ".
   * Field value is ignored if validityPeriod is bigger than zero.
   * The date format must follow ISO_8601. If 'Z' is written immediately after the time, it is considered UTC.
   * Time offset from UTC can be appended instead of 'Z' using plus or minus signs. Negative UTC offsets describe a time zone west of UTC�00:00, where the civil time is behind (or earlier) than UTC. Positive UTC offsets describe a time zone east of UTC�00:00, where the civil time is ahead (or later) than UTC
   */
  validTo?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const offerAssignmentSchema: Schema<OfferAssignment> = typedExpandoObject(
  {
    referenceId: ['referenceId', string()],
    consumerUuid: ['consumerUuid', string()],
    offerId: ['offerId', string()],
    validFrom: ['validFrom', optional(string())],
    validityPeriod: ['validityPeriod', optional(number())],
    validTo: ['validTo', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
