/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface PointsToCash {
  /** The points used for converting it to cash */
  pointsRedeemed?: number;
  /** Total amount in cash used */
  totalAmount?: number;
  /** Indication if the p2c was used as a method of payment */
  pointsToCashMop?: boolean;
  additionalProperties?: Record<string, unknown>;
}

export const pointsToCashSchema: Schema<PointsToCash> = typedExpandoObject(
  {
    pointsRedeemed: ['pointsRedeemed', optional(number())],
    totalAmount: ['totalAmount', optional(number())],
    pointsToCashMop: ['pointsToCashMOP', optional(boolean())],
  },
  'additionalProperties',
  optional(unknown())
);
