/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ProductType
 */
export enum ProductType {
  Fuel = 'FUEL',
  Cr = 'CR',
  Cc = 'CC',
  Partner = 'PARTNER',
  Other = 'OTHER',
  GreenEnergy = 'GREEN_ENERGY',
}

/**
 * Schema for ProductType
 */
export const productTypeSchema: Schema<ProductType> = stringEnum(ProductType);
