/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { RedemptionItem, redemptionItemSchema } from './redemptionItem.js';

export interface RedemptionRequest {
  /**
   * The SSO uuid of the user signed in with Shell credentials.
   * Format: 32 hexadecimal digits grouped the following way: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
   * See: https://www.wikiwand.com/en/Universally_unique_identifier#/Format
   */
  uuid: string;
  /** A unique ID for the transaction from the partner. Used to identify duplicate requests. */
  referenceId: string;
  /** Specifies the number of points to be redeemed from the user's point balance and the reason for redemption, which will also be shown to the user. Mutiple redemption items can be submitted in a single API request. */
  redemptionReqArray: RedemptionItem[];
  additionalProperties?: Record<string, unknown>;
}

export const redemptionRequestSchema: Schema<RedemptionRequest> = lazy(() =>
  typedExpandoObject(
    {
      uuid: ['uuid', string()],
      referenceId: ['referenceId', string()],
      redemptionReqArray: ['redemptionReqArray', array(redemptionItemSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
