/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  RedemptionResponseItem,
  redemptionResponseItemSchema,
} from './redemptionResponseItem.js';

export interface RedemptionResponse {
  /** A unique Reference ID for the transaction, generated by the partner. */
  referenceId: string;
  /** The time and date of the redemption transaction. */
  transactionDateTime: string;
  /** The user's current loyalty point balance after the requested items have been redeemed. */
  updatedPointBalance: string;
  /** This array requests the points to be redeemed from the users point balance for the items requested. The same information will be shown to the user. Multiple items can be redeemed in a single API request. */
  redemptionReqArray: RedemptionResponseItem[];
  additionalProperties?: Record<string, unknown>;
}

export const redemptionResponseSchema: Schema<RedemptionResponse> = lazy(() =>
  typedExpandoObject(
    {
      referenceId: ['referenceId', string()],
      transactionDateTime: ['transactionDateTime', string()],
      updatedPointBalance: ['updatedPointBalance', string()],
      redemptionReqArray: [
        'redemptionReqArray',
        array(redemptionResponseItemSchema),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
