/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ProductType, productTypeSchema } from './productType.js';

export interface RedeemedItemProduct {
  /** Unique Id of the product */
  id: string;
  /** Name of the product */
  name: string;
  /** Indicating the Type of the product (Fuel, CR, CC, PARTNER, OTHER, GREEN_ENERGY). */
  productType: ProductType;
  /** Reason for redemption of points as mentioned by the partner. reasonForRedemption to be populated only for redeemedItems (not for saleItems) when productType = PARTNER. */
  reasonForRedemption?: string;
  /** Product code of gift item (euroShell Forward Code). To be populated with 3 digit Euroshell product code. */
  productCode?: string;
  productDescription?: string;
  additionalProperties?: Record<string, unknown>;
}

export const redeemedItemProductSchema: Schema<RedeemedItemProduct> = typedExpandoObject(
  {
    id: ['id', string()],
    name: ['name', string()],
    productType: ['productType', productTypeSchema],
    reasonForRedemption: ['reasonForRedemption', optional(string())],
    productCode: ['productCode', optional(string())],
    productDescription: ['productDescription', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
