/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { OfferInfo, offerInfoSchema } from './offerInfo.js';
import { OfferLanguage, offerLanguageSchema } from './offerLanguage.js';
import {
  RedeemedItemProduct,
  redeemedItemProductSchema,
} from './redeemedItemProduct.js';
import {
  TransactionDetailType,
  transactionDetailTypeSchema,
} from './transactionDetailType.js';
import { VoucherItem, voucherItemSchema } from './voucherItem.js';

export interface RedeemedItem {
  /** Description - currently not in use */
  description?: string;
  /** Total amount */
  amount: number;
  /** Indicates the Type of the transaction detail row (award, redemption, transfer, voucher, refund or central award). */
  detailType: TransactionDetailType;
  /** Discount amount of sales line */
  discountAmount: number;
  offerInfos: OfferInfo[];
  offerLang?: OfferLanguage;
  /** Original amount of sales line */
  originalAmount: number;
  productData: RedeemedItemProduct;
  /** Quantity of product */
  quantity: number;
  /** Value added tax */
  vatAmount?: number;
  /** VAT rate of sales line */
  vatRate?: number;
  /** Number of points redeemed. Applicable for redeemedItems and not for saleItems */
  points?: number;
  /** List of vouchers */
  vouchers?: string[];
  voucherItems?: VoucherItem[];
  additionalProperties?: Record<string, unknown>;
}

export const redeemedItemSchema: Schema<RedeemedItem> = lazy(() =>
  typedExpandoObject(
    {
      description: ['description', optional(string())],
      amount: ['amount', number()],
      detailType: ['detailType', transactionDetailTypeSchema],
      discountAmount: ['discountAmount', number()],
      offerInfos: ['offerInfos', array(offerInfoSchema)],
      offerLang: ['offerLang', optional(offerLanguageSchema)],
      originalAmount: ['originalAmount', number()],
      productData: ['productData', redeemedItemProductSchema],
      quantity: ['quantity', number()],
      vatAmount: ['vatAmount', optional(number())],
      vatRate: ['vatRate', optional(number())],
      points: ['points', optional(number())],
      vouchers: ['vouchers', optional(array(string()))],
      voucherItems: ['voucherItems', optional(array(voucherItemSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
