/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface RedemptionItem {
  /** The itemID identifies the catalogue item in the loyalty system. Shell will set these up and share the IDs with the partner. */
  itemId: string;
  /** Number of items redeemed on the user's behalf. If the quantity is not specified, the system will assume a default quantity of 1. This is not used for the calculation of points, but only for displaying to the user. */
  quantity?: number;
  /** Total number of points to be redeemed from the Shell Loyalty Platform for this item. */
  points: number;
  /** Reason for the points redemption. This attribute will be shown to the customer via app/web channel under Transaction History. */
  reasonForRedemption: string;
  additionalProperties?: Record<string, unknown>;
}

export const redemptionItemSchema: Schema<RedemptionItem> = typedExpandoObject(
  {
    itemId: ['itemId', string()],
    quantity: ['quantity', optional(number())],
    points: ['points', number()],
    reasonForRedemption: ['reasonForRedemption', string()],
  },
  'additionalProperties',
  optional(unknown())
);
