/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface RedemptionResponseItem {
  /** Unique Item ID for the transaction from the partner. Used to identify the catalogue item in the Shell Loyalty Platform. Each Partner will have one or more items set up in the Shell Loyalty Platform. */
  itemId?: string;
  /** The quantity of the items required. */
  quantity?: number;
  /** The number of points that will be redemmed from the Shell Loyalty Platform. */
  points?: number;
  /** The reason for the points redemption. This attribute will be shown in the Transaction History feture. */
  reasonForRedemption?: string;
  additionalProperties?: Record<string, unknown>;
}

export const redemptionResponseItemSchema: Schema<RedemptionResponseItem> = typedExpandoObject(
  {
    itemId: ['itemId', optional(string())],
    quantity: ['quantity', optional(number())],
    points: ['points', optional(number())],
    reasonForRedemption: ['reasonForRedemption', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
