/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface RefreshTokenResponse {
  accessToken: string;
  refreshToken: string;
  /** Indicates the number of seconds until the new access token provided in the pair expires */
  expiresIn: number;
  additionalProperties?: Record<string, unknown>;
}

export const refreshTokenResponseSchema: Schema<RefreshTokenResponse> = typedExpandoObject(
  {
    accessToken: ['accessToken', string()],
    refreshToken: ['refreshToken', string()],
    expiresIn: ['expiresIn', number()],
  },
  'additionalProperties',
  optional(unknown())
);
