/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface RefreshTokenRequest {
  /** The refresh token which was provided from the exchangeAccessCode end point. */
  refreshToken: string;
  additionalProperties?: Record<string, unknown>;
}

export const refreshTokenRequestSchema: Schema<RefreshTokenRequest> = typedExpandoObject(
  { refreshToken: ['refreshToken', string()] },
  'additionalProperties',
  optional(unknown())
);
