/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ProductType, productTypeSchema } from './productType.js';

export interface SaleItemProduct {
  /** Unique Id of the product */
  id: string;
  /** Name of the product */
  name: string;
  /** Indicating the Type of the product (Fuel, CR, CC, PARTNER, OTHER, GREEN_ENERGY). */
  productType: ProductType;
  /** Product code of gift item (euroShell Forward Code). To be populated with 3 digit Euroshell product code. */
  productCode?: string;
  productDescription?: string;
  /** Customer name of the product provided by the partner */
  additionalProductDescription?: string;
  additionalProperties?: Record<string, unknown>;
}

export const saleItemProductSchema: Schema<SaleItemProduct> = typedExpandoObject(
  {
    id: ['id', string()],
    name: ['name', string()],
    productType: ['productType', productTypeSchema],
    productCode: ['productCode', optional(string())],
    productDescription: ['productDescription', optional(string())],
    additionalProductDescription: [
      'additionalProductDescription',
      optional(string()),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
