/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  EvChargingDetails,
  evChargingDetailsSchema,
} from './evChargingDetails.js';
import { OfferInfo, offerInfoSchema } from './offerInfo.js';
import { OfferLanguage, offerLanguageSchema } from './offerLanguage.js';
import { SaleItemProduct, saleItemProductSchema } from './saleItemProduct.js';
import {
  TransactionDetailType,
  transactionDetailTypeSchema,
} from './transactionDetailType.js';
import { UnitMeasure, unitMeasureSchema } from './unitMeasure.js';
import { VoucherItem, voucherItemSchema } from './voucherItem.js';

export interface SaleItem {
  /** Description - currently not in use */
  description?: string;
  /** Total amount */
  amount: number;
  /** Indicates the Type of the transaction detail row (award, redemption, transfer, voucher, refund or central award). */
  detailType: TransactionDetailType;
  /** Discount amount of sales line */
  discountAmount: number;
  offerInfos: OfferInfo[];
  offerLang?: OfferLanguage;
  /** Original amount of sales line */
  originalAmount: number;
  /** Original amount excluding VAT */
  originalNetAmount?: number;
  productData: SaleItemProduct;
  /** Quantity of product */
  quantity: number;
  /** Value added tax */
  vatAmount?: number;
  /** VAT rate of sales line */
  vatRate?: number;
  voucherItems?: VoucherItem[];
  /** List of vouchers */
  vouchers?: string[];
  /** Unit price of sale item */
  unitPrice?: number;
  /** Unit of measure */
  unitMeasure?: UnitMeasure;
  ev?: EvChargingDetails;
  /** Points earned in a transaction */
  points?: number;
  additionalProperties?: Record<string, unknown>;
}

export const saleItemSchema: Schema<SaleItem> = lazy(() =>
  typedExpandoObject(
    {
      description: ['description', optional(string())],
      amount: ['amount', number()],
      detailType: ['detailType', transactionDetailTypeSchema],
      discountAmount: ['discountAmount', number()],
      offerInfos: ['offerInfos', array(offerInfoSchema)],
      offerLang: ['offerLang', optional(offerLanguageSchema)],
      originalAmount: ['originalAmount', number()],
      originalNetAmount: ['originalNetAmount', optional(number())],
      productData: ['productData', saleItemProductSchema],
      quantity: ['quantity', number()],
      vatAmount: ['vatAmount', optional(number())],
      vatRate: ['vatRate', optional(number())],
      voucherItems: ['voucherItems', optional(array(voucherItemSchema))],
      vouchers: ['vouchers', optional(array(string()))],
      unitPrice: ['unitPrice', optional(number())],
      unitMeasure: ['unitMeasure', optional(unitMeasureSchema)],
      ev: ['EV', optional(evChargingDetailsSchema)],
      points: ['points', optional(number())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
