/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SiteData {
  /** Two character ISO 3166-1 alpha-2 country code */
  countryCode: string;
  /** Unique Id of the site */
  siteId: string;
  /** Name of the site */
  name: string;
  /** Postcode of the site */
  postcode?: string;
  /** City of the site */
  city?: string;
  /** Address of the site */
  address?: string;
  additionalProperties?: Record<string, unknown>;
}

export const siteDataSchema: Schema<SiteData> = typedExpandoObject(
  {
    countryCode: ['countryCode', string()],
    siteId: ['siteId', string()],
    name: ['name', string()],
    postcode: ['postcode', optional(string())],
    city: ['city', optional(string())],
    address: ['address', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
