/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  TransactionDetailType,
  transactionDetailTypeSchema,
} from './transactionDetailType.js';

export interface TransactionVoucher {
  /** Indicates the Type of the transaction detail row (award, redemption, transfer, voucher, refund or central award). */
  detailType: TransactionDetailType;
  /** Unique code of the voucher */
  code: string;
  /** Name of the voucher */
  name: string;
  /** Sum amount of the voucher */
  amount: number;
  /** Quantity of vouchers */
  quantity: number;
  additionalProperties?: Record<string, unknown>;
}

export const transactionVoucherSchema: Schema<TransactionVoucher> = typedExpandoObject(
  {
    detailType: ['detailType', transactionDetailTypeSchema],
    code: ['code', string()],
    name: ['name', string()],
    amount: ['amount', number()],
    quantity: ['quantity', number()],
  },
  'additionalProperties',
  optional(unknown())
);
