/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransactionTypeFilter
 */
export enum TransactionTypeFilter {
  Earn = 'EARN',
  Spent = 'SPENT',
  All = 'ALL',
}

/**
 * Schema for TransactionTypeFilter
 */
export const transactionTypeFilterSchema: Schema<TransactionTypeFilter> = stringEnum(
  TransactionTypeFilter
);
