/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  TransactionBalanceState,
  transactionBalanceStateSchema,
} from './transactionBalanceState.js';

export interface TransactionBalanceAmount {
  /** Current value of specified balance */
  amount: number;
  /** State of the amount */
  state: TransactionBalanceState;
  additionalProperties?: Record<string, unknown>;
}

export const transactionBalanceAmountSchema: Schema<TransactionBalanceAmount> = typedExpandoObject(
  {
    amount: ['amount', number()],
    state: ['state', transactionBalanceStateSchema],
  },
  'additionalProperties',
  optional(unknown())
);
