/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransactionCurrencyType
 */
export enum TransactionCurrencyType {
  Qv = 'QV',
  Point = 'POINT',
  Stamp = 'STAMP',
  Airmiles = 'AIRMILES',
  Miles = 'MILES',
  Cash = 'CASH',
  StampCounter = 'STAMP_COUNTER',
}

/**
 * Schema for TransactionCurrencyType
 */
export const transactionCurrencyTypeSchema: Schema<TransactionCurrencyType> = stringEnum(
  TransactionCurrencyType
);
