/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  TransactionBalanceAmount,
  transactionBalanceAmountSchema,
} from './transactionBalanceAmount.js';
import {
  TransactionCurrencyType,
  transactionCurrencyTypeSchema,
} from './transactionCurrencyType.js';

export interface TransactionBalance {
  /** Type of balance */
  currencyType: TransactionCurrencyType;
  amounts: TransactionBalanceAmount[];
  additionalProperties?: Record<string, unknown>;
}

export const transactionBalanceSchema: Schema<TransactionBalance> = lazy(() =>
  typedExpandoObject(
    {
      currencyType: ['currencyType', transactionCurrencyTypeSchema],
      amounts: ['amounts', array(transactionBalanceAmountSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
