/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Transaction, transactionSchema } from './transaction.js';

export interface TransactionsResponse {
  /** Total no of resource which will be sent back across all pages */
  totalResults: number;
  /** API URI which must be used to retrieve the next page of resources */
  nextPage: string;
  /** API URI which must be used to retrieve the previous page of resources */
  previousPage: string;
  /** Total amount saved so far */
  totalSaved: number;
  /** Transactions list */
  transactions: Transaction[];
  additionalProperties?: Record<string, unknown>;
}

export const transactionsResponseSchema: Schema<TransactionsResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        totalResults: ['totalResults', number()],
        nextPage: ['nextPage', string()],
        previousPage: ['previousPage', string()],
        totalSaved: ['totalSaved', number()],
        transactions: ['transactions', array(transactionSchema)],
      },
      'additionalProperties',
      optional(unknown())
    )
);
