/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransactionBalanceState
 */
export enum TransactionBalanceState {
  Available = 'AVAILABLE',
  Expiring = 'EXPIRING',
  Reserved = 'RESERVED',
  Target = 'TARGET',
  Boost = 'BOOST',
  Change = 'CHANGE',
  TotalSpent = 'TOTAL_SPENT',
  Earned = 'EARNED',
  Redeemed = 'REDEEMED',
}

/**
 * Schema for TransactionBalanceState
 */
export const transactionBalanceStateSchema: Schema<TransactionBalanceState> = stringEnum(
  TransactionBalanceState
);
