/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TransactionDetailType
 */
export enum TransactionDetailType {
  Award = 'AWARD',
  Redemption = 'REDEMPTION',
  Transfer = 'TRANSFER',
  Refund = 'REFUND',
  CentralAward = 'CENTRAL_AWARD',
  Voucher = 'VOUCHER',
}

/**
 * Schema for TransactionDetailType
 */
export const transactionDetailTypeSchema: Schema<TransactionDetailType> = stringEnum(
  TransactionDetailType
);
