/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CurrencyData, currencyDataSchema } from './currencyData.js';
import { LoyaltyCardInfo, loyaltyCardInfoSchema } from './loyaltyCardInfo.js';
import { PointsToCash, pointsToCashSchema } from './pointsToCash.js';
import { RedeemedItem, redeemedItemSchema } from './redeemedItem.js';
import { SaleItem, saleItemSchema } from './saleItem.js';
import { SiteData, siteDataSchema } from './siteData.js';
import {
  TransactionBalance,
  transactionBalanceSchema,
} from './transactionBalance.js';
import {
  TransactionVoucher,
  transactionVoucherSchema,
} from './transactionVoucher.js';

export interface Transaction {
  /** Transaction date as Unix epoch (UTC), as requested by MobGen. */
  transactionDateTime: bigint;
  /** Transaction date in JSON recommended format: “yyyy-MM-ddTHH:mm:ssZ” */
  transactionDateTimeStamp?: string;
  siteData: SiteData;
  loyalty: LoyaltyCardInfo;
  /** Unique Id of the transaction row. */
  transactionId?: string;
  /** Unique code identifying the partner */
  partnerCode?: string;
  /** Name of the partner */
  partnerName?: string;
  partnerLogo?: string;
  /** Reference ID for each transaction. It is unique for each partner and transaction. */
  referenceId?: string;
  /** Total amount of the transaction. */
  totalAmount: number;
  /** Total discount amount of the transaction. */
  totalDiscountAmount: number;
  /** totalAmount - totalDiscountedFullAmount */
  totalDiscountedFullAmount: number;
  /** Total amount of VAT */
  totalVatAmount?: number;
  balances?: TransactionBalance[];
  /** Currency using ISO4217 alpha-3 currency code */
  currencyCode?: string;
  saleItems: SaleItem[];
  redeemedItems: RedeemedItem[];
  transactionVouchers: TransactionVoucher[];
  /** Unique number of transaction's receipt */
  receiptNumber?: string;
  pointsToCash?: PointsToCash;
  /** Partner identifier */
  companyId?: bigint;
  /** Describes whether the transaction is partner redemption. */
  isPartnerRedemption?: boolean;
  /** currencyData is only filled, where there is possible non-same currency cross-border transaction */
  currencyData?: CurrencyData;
  additionalProperties?: Record<string, unknown>;
}

export const transactionSchema: Schema<Transaction> = lazy(() =>
  typedExpandoObject(
    {
      transactionDateTime: ['transactionDateTime', bigint()],
      transactionDateTimeStamp: [
        'transactionDateTimeStamp',
        optional(string()),
      ],
      siteData: ['siteData', siteDataSchema],
      loyalty: ['loyalty', loyaltyCardInfoSchema],
      transactionId: ['transactionId', optional(string())],
      partnerCode: ['partnerCode', optional(string())],
      partnerName: ['partnerName', optional(string())],
      partnerLogo: ['partnerLogo', optional(string())],
      referenceId: ['referenceId', optional(string())],
      totalAmount: ['totalAmount', number()],
      totalDiscountAmount: ['totalDiscountAmount', number()],
      totalDiscountedFullAmount: ['totalDiscountedFullAmount', number()],
      totalVatAmount: ['totalVatAmount', optional(number())],
      balances: ['balances', optional(array(transactionBalanceSchema))],
      currencyCode: ['currencyCode', optional(string())],
      saleItems: ['saleItems', array(saleItemSchema)],
      redeemedItems: ['redeemedItems', array(redeemedItemSchema)],
      transactionVouchers: [
        'transactionVouchers',
        array(transactionVoucherSchema),
      ],
      receiptNumber: ['receiptNumber', optional(string())],
      pointsToCash: ['pointsToCash', optional(pointsToCashSchema)],
      companyId: ['companyId', optional(bigint())],
      isPartnerRedemption: ['isPartnerRedemption', optional(boolean())],
      currencyData: ['currencyData', optional(currencyDataSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
