/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import { Fault, faultSchema } from './fault.js';

/** The application is not authorised to use the requested grant type. */
export interface UnauthorizedError {
  fault?: Fault;
}

export const unauthorizedErrorSchema: Schema<UnauthorizedError> = lazy(() =>
  object({ fault: ['fault', optional(faultSchema)] })
);
