/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for UnitMeasure
 */
export enum UnitMeasure {
  Kw = 'KW',
  Litre = 'LITRE',
  Each = 'EACH',
}

/**
 * Schema for UnitMeasure
 */
export const unitMeasureSchema: Schema<UnitMeasure> = stringEnum(UnitMeasure);
