/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface VoucherItem {
  /** Voucher code */
  code: string;
  /** Expiry date as Unix epoch (UTC), as requested by MobGen. */
  expiryDate: bigint;
  /** Expiry date in JSON recommended format: “yyyy-MM-ddTHH:mm:ssZ” */
  expiryDateTimestamp: string;
  additionalProperties?: Record<string, unknown>;
}

export const voucherItemSchema: Schema<VoucherItem> = typedExpandoObject(
  {
    code: ['code', string()],
    expiryDate: ['expiryDate', bigint()],
    expiryDateTimestamp: ['expiryDateTimestamp', string()],
  },
  'additionalProperties',
  optional(unknown())
);
