/**
 * Loyalty APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  accessTokenAuthenticationProvider,
  compositeAuthenticationProvider,
  customHeaderAuthenticationProvider,
  OAuthConfiguration,
  requestAuthenticationProvider,
} from './authentication.js';
import { ClientAuthorizationTokenManager } from './clientAuthorizationTokenManager.js';
import { Configuration } from './configuration.js';
import { OauthToken } from './models/oauthToken.js';

export function createAuthProviderFromConfig(
  config: Partial<Configuration>,
  clientAuthorizationToken: () => ClientAuthorizationTokenManager | undefined
) {
  const authConfig = {
    publicBearerToken:
      config.publicBearerTokenCredentials &&
      accessTokenAuthenticationProvider(config.publicBearerTokenCredentials),
    publicBasicToken:
      config.publicBasicTokenCredentials &&
      customHeaderAuthenticationProvider(config.publicBasicTokenCredentials),
    privateBasicToken:
      config.privateBasicTokenCredentials &&
      customHeaderAuthenticationProvider(config.privateBasicTokenCredentials),
    clientAuthorizationToken:
      config.clientAuthorizationTokenCredentials &&
      requestAuthenticationProvider(
        config.clientAuthorizationTokenCredentials.oauthToken,
        clientAuthorizationTokenTokenProvider(
          clientAuthorizationToken,
          config.clientAuthorizationTokenCredentials.oauthTokenProvider
        ),
        config.clientAuthorizationTokenCredentials.oauthOnTokenUpdate,
        {
          clockSkew: config.clientAuthorizationTokenCredentials.oauthClockSkew,
        } as OAuthConfiguration
      ),
    customerHeader:
      config.customerHeaderCredentials &&
      customHeaderAuthenticationProvider(config.customerHeaderCredentials),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}

function clientAuthorizationTokenTokenProvider(
  clientAuthorizationToken: () => ClientAuthorizationTokenManager | undefined,
  defaultProvider:
    | ((
        lastOAuthToken: OauthToken | undefined,
        authManager: ClientAuthorizationTokenManager
      ) => Promise<OauthToken>)
    | undefined
): ((token: OauthToken | undefined) => Promise<OauthToken>) | undefined {
  return (token: OauthToken | undefined) => {
    const manager = clientAuthorizationToken();
    if (manager === undefined) {
      throw Error('Unable to find the OAuthManager instance');
    }
    if (defaultProvider === undefined) {
      return manager.updateToken(token);
    }
    return defaultProvider(token, manager);
  };
}
